name: water_analytics_australia
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  chucker_flutter: ^1.7.2
  clipboard: ^0.1.3
  cloud_firestore: ^4.3.1
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  custom_pop_up_menu: ^1.2.4
  data_table_2: ^2.5.12
  dio: ^5.4.3+1
  dotted_line: ^3.2.2
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  excel: ^4.0.3
  firebase_auth: ^4.19.5
  firebase_core: ^2.30.1
  firebase_remote_config: ^4.4.5
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.10+2
  flutter_bloc: ^8.1.4
  flutter_hooks: ^0.20.5
  flutter_widget_from_html: ^0.14.11
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  heroicons: ^0.10.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  linked_scroll_controller: ^0.2.0
  loading_animation_widget: ^1.2.1
  odoo_rpc: ^0.5.4
  path: ^1.9.0
  path_provider: ^2.1.3
  responsive_framework: ^1.4.0
  shimmer: ^3.0.0
  xml_rpc: ^0.5.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/wa_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/wa_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
    
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
