// import "package:water_analytics_australia/1_domain/models/landing_price_model.dart";

// List<LandingPrice> landingPrices = [
//   const LandingPrice(
//     "name": "WAA Full House Healthy Water V2-B (w filters)",
//     "internal_reference": "FHWR-3S1-20-B",
//     "product_category": "System",
//     "installation_service": 4190,
//     "supply_only": 3390,
//   ),
//   const LandingPrice(
//     "name": "WAA Full House Healthy Water V2-W (w filters)",
//     "internal_reference": "FHWR-3S1-20-W",
//     "product_category": "System",
//     "installation_service": 4390,
//     "supply_only": 3590,
//   ),
//   const LandingPrice(
//     "name": "WAA Healthy Independent Undersink 6 Stages V1 (w filters)",
//     "internal_reference": "USRO-6S1-2W",
//     "product_category": "System",
//     "installation_service": 1490,
//     "supply_only": 1190,
//   ),
//   const LandingPrice(
//     "name": "WAA Healthy Under Sink RO2 (w filters)",
//     "internal_reference": "USRO-3S1-2W",
//     "product_category": "System",
//     "installation_service": 300,
//     "supply_only": 300,
//   ),
//   const LandingPrice(
//     "name": "3 Way Mixer 7604B (L Circular)",
//     "internal_reference": "3WM 7604B",
//     "product_category": "System",
//     "installation_service": 300,
//     "supply_only": 300,
//   ),
//   const LandingPrice(
//     "name": "3 Way Mixer 7604G (L Circular)",
//     "internal_reference": "3WM 7604G",
//     "product_category": "Taps",
//     "installation_service": 300,
//     "supply_only": 300,
//   ),
//   const LandingPrice(
//     "name": "3 Way Mixer 7604N (L Circular)",
//     "internal_reference": "3WM 7604N",
//     "product_category": "Taps",
//     "installation_service": 300,
//     "supply_only": 300,
//   ),
//   const LandingPrice(
//     "name": "3 Way Mixer 7604S (L Circular)",
//     "internal_reference": "3WM 7604S",
//     "product_category": "Taps",
//     "installation_service": 300,
//     "supply_only": 300,
//   ),
//   const LandingPrice(
//     "name": "3 Way Mixer 7605B (U)",
//     "internal_reference": "3WM 7605B",
//     "product_category": "Taps",
//     "installation_service": 300,
//     "supply_only": 300,
//   ),
//   const LandingPrice(
//     "name": "3 Way Mixer 7605N (U)",
//     "internal_reference": "3WM 7605N",
//     "product_category": "Taps",
//     "installation_service": 300,
//     "supply_only": 300,
//   ),
//   const LandingPrice(
//     "name": "3 Way Mixer 7605S (U)",
//     "internal_reference": "3WM 7605S",
//     "product_category": "Taps",
//     "installation_service": 300,
//     "supply_only": 300,
//   ),
//   const LandingPrice(
//     "name": "3 Way Mixer 7606B (L Flat)",
//     "internal_reference": "3WM 7606B",
//     "product_category": "Taps",
//     "installation_service": 300,
//     "supply_only": 300,
//   ),
//   const LandingPrice(
//     "name": "3 Way Mixer 7606N (L Flat)",
//     "internal_reference": "3WM 7606N",
//     "product_category": "Taps",
//     "installation_service": 300,
//     "supply_only": 300,
//   ),
//   const LandingPrice(
//     "name": "3 Way Mixer 7606S (L Flat)",
//     "internal_reference": "3WM 7606S",
//     "product_category": "Taps",
//     "installation_service": 300,
//     "supply_only": 300,
//   ),
//   const LandingPrice(
//     "name": "3 Way Mixer 7624B (U Detachable)",
//     "internal_reference": "3WM 7624B",
//     "product_category": "Taps",
//     "installation_service": 300,
//     "supply_only": 300,
//   ),
//   const LandingPrice(
//     "name": "3 Way Mixer 7624G (U Detachable)",
//     "internal_reference": "3WM 7624G",
//     "product_category": "Taps",
//     "installation_service": 400,
//     "supply_only": 400,
//   ),
//   const LandingPrice(
//     "name": "3 Way Mixer 7624N (U Detachable)",
//     "internal_reference": "3WM 7624N",
//     "product_category": "Taps",
//     "installation_service": 400,
//     "supply_only": 400,
//   ),
//   const LandingPrice(
//     "name": "3 Way Mixer 7624S (U Detachable)",
//     "internal_reference": "3WM 7624S",
//     "product_category": "Taps",
//     "installation_service": 400,
//     "supply_only": 400,
//   ),
// ];
